### ISSUE TITLE
Avoid Sentence Splitting

### ISSUE THREAD

**Issue by NeverInAsh** [bionlplab/isimp#2]
Hi, Thanks for this amazing library and the paper accompanying it.

There is one issue that I found. Some sentences are getting split automatically. I did some research and found that this is due to the stanfordcorenlp pipeline.

and also punctuations are getting added with spaces around them like (entity) => ( entity )

These two things should not automatically happen (As i said this is happening due to stanford pipeline).

Is it possible to avoid this issue, especially sentence splitting.

**Comment by yfpeng** [comment]
I agree with you that no extra spaces should be added. Unfortunately, I do not actively maintain the package. You are welcome to send pull requests, should you find a way to solve the issue.
